sudo: required
services:
  - docker
before_install:
  - docker build -t desh1993/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true desh1993/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "Docker-react"
  env: "Docker-react-env"
  bucket_name:  "elasticbeanstalk-ap-southeast-2-025237549146"
  bucket_path: "Docker-react"
  on:
    branch:main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"