# Create image based on the official Node image from dockerhub
FROM node:16-alpine AS builder

# Create app directory
WORKDIR /app

# Copy dependency definitions
COPY package.json .
COPY package-lock.json .

# Install dependecies
#RUN npm set progress=false \
#    && npm config set depth 0 \
#    && npm i install
RUN npm install

# Get all the code needed to run the app
COPY . .
RUN npm run build

FROM nginx
EXPOSE 80
COPY --from=builder /app/build /usr/share/nginx/html 