# Use the official Node.js 16 image as the builder
FROM node:16-alpine as builder

# Set the working directory in the builder image
WORKDIR '/app'

# Copy the package.json and install dependencies
COPY package.json .
RUN apk update && apk add --no-cache curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | sh -
RUN apk update && apk add --no-cache nodejs npm
RUN npm install

# Copy the application code and build
COPY . .
RUN npm run build

# Use the official Nginx image as the final image
FROM nginx

# Expose port 80
EXPOSE 80

# Copy the built files from the builder image to the Nginx image
COPY --from=builder /app/build /usr/share/nginx/html
